services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: icn
      POSTGRES_USER: icn
      POSTGRES_DB: icn
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  event-store:
    build:
      context: ../services/event-store
    environment:
      RUST_LOG: info
      LOG_FORMAT: json
      OTEL_SERVICE_NAME: event-store
    env_file:
      - ../.env
    ports: ["8081:8081"]

  governance-engine:
    build:
      context: ../services/governance-engine
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      LOG_FORMAT: json
      OTEL_SERVICE_NAME: governance
    env_file:
      - ../.env
    ports: ["8000:8000"]

  api-gateway:
    build:
      context: ../services/api-gateway
    environment:
      LOG_FORMAT: json
      OTEL_SERVICE_NAME: api-gateway
    env_file:
      - ../.env
    ports: ["8080:8080"]
    depends_on: [event-store]

  discovery:
    build:
      context: ../services/discovery
    environment:
      LOG_FORMAT: json
      OTEL_SERVICE_NAME: discovery
    env_file:
      - ../.env
    ports: ["8090:8090"]

volumes:
  pg_data: {}
  redis_data: {}

