proposal_types:
  economic:
    name: "Economic Decision"
    description: "Decisions affecting financial resources or economic relationships"
    default_governance_model: consensus_minus_one
    required_roles: ["member"]
    auto_approval_conditions:
      - "amount <= 100 AND proposer.reputation >= 4.0"
    stakeholder_notification: "affected_cooperatives"
  policy:
    name: "Policy Change"
    description: "Changes to cooperative policies or procedures"
    default_governance_model: consensus
    required_roles: ["member"]
    expert_review_required: false
    stakeholder_notification: "all_members"
  membership:
    name: "Membership Decision"
    description: "Decisions about member admission, suspension, or termination"
    default_governance_model: consensus_minus_one
    required_roles: ["board_member", "membership_committee"]
    confidential: true
    stakeholder_notification: "board_members"
  infrastructure:
    name: "Infrastructure Investment"
    description: "Major infrastructure or technology investments"
    default_governance_model: supermajority
    required_roles: ["member"]
    expert_review_required: true
    financial_analysis_required: true
    stakeholder_notification: "all_network_members"
    minimum_discussion_period_days: 14


